---
- name: Установка Nginx и настройка странички
  hosts: web
  become: yes

  tasks:

    - name: Установка Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
    
    - name: Запуск Nginx
      service:
        name: nginx
        state: started
        enabled: yes
    
    - name: Создание HTML-странички
      copy:
        #content: "<html><head> <title>Welcome to My Website!</title></head><body><h1>Netology Diplom!</h1><p>Welcome to my custom homepage!</p></body></html>"
        content: |
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <meta http-equiv="X-UA-Compatible" content="ie=edge">
              <title>My Website</title>
              <link rel="stylesheet" href="./style.css">
              <link rel="icon" href="./favicon.ico" type="image/x-icon">
          </head>
          <body bgcolor="#C7FCEC">
            <main>
                 <h1>Netology Diplom!</h1>  
                 <p><a href="http://158.160.76.163/zabbix/"><h1>Zabbix</a></p>
            </main>
            <script src="index.js"></script> 
          </body>
          </html>
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data

      notify:
        - Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
